-- AlterTable
ALTER TABLE "Negotiation" ADD COLUMN     "totalCostUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalTokens" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "maxRounds" SET DEFAULT 4;
